---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.10"}]
  - name: centos-6.4
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.11"}]

suites:
  - name: default
    run_list:
      - recipe[server-bootstrap::default]
      - recipe[server-bootstrap::hosts-file]
      - recipe[server-bootstrap::adjust-clock]
      - recipe[server-bootstrap::ssh-hardening]
    attributes:
